open:
  api:
    title: My API
    version: 1.0.0
    description: API Documentation for My Application
    serverUrl: http://localhost:8080
    serverName: Local Server
  

google:
  client-id: YOUR_GOOGLE_CLIENT_ID
  client-secret: YOUR_GOOGLE_CLIENT_SECRET
  redirect-uri: http://localhost:8080/auth/google/callback